---
# handlers file for ansible-kea-dhcp
- name: restart kea-dhcp
  service:
    name: "{{ item['name'] }}"
    state: restarted
  become: true
  throttle: 1
  #order: reverse_inventory
  loop: "{{ kea_dhcp_services }}"
  when:
    - item['enabled']|bool
